sudo: false
language: node_js
node_js:
  - '6'
  - '8'
  - '10'
deploy:
  provider: npm
  email:
    secure: eBA0iQEguGYOpSZgEliD0yxorTAIiTXOvGhkIfhMLosk6KiNajkzBTYZO3wWK77sr1RA2PO0x4zQidkK+rRgpvamu8JbyBt6uvQo+QmLrWqCdRnHUO/tXx8f1mmlrymrgFUjlbtrMkAp8+YnArzeIeKBUFSv0GDYIxxYJDVzHghiHHPSp0PWcju6BMPGHbfZy2LVfacI8Zl5uUsS+jUDQGAhXQDKkJqIU6SxBMG2leuw6PrfsQL8BgBW/0O9sew85gpVxRTGfBUPLrvtdim4y8ZVIRVdKpgI272Xf/D2ADuA3H06/nABcqgsuLGNwWBG8n6clidisaTJ27ShUKqQF3YTKPCXMIZj2tbeZ4S9dlwOlE51/n/dY3S/F7QgtnOW6QTUTXU1gBsS8OU1fRnYdkl6p3fZ4X4fxW85PX12kHcaNMr5BIQj0FsdWxz6dfKaJnTGTuu0TPMv8CDND8w5S028bKDu0vS6v7lYUkRlk5/fFJZEdeSQ7wiPRGhQrOsCiYBvhIj1n2WZzRktvNBV4bw/JWC1nlPlWOhQT8XisEgeeyXoidnV23Ng/fsiGRnIWf1hatSg5IPg1hEuiA0tE6NIENrCs4jfXsywHYnH1/lvsT+8LFu5xp5yNMPZ4voXMsC6FaiTv3wW7OhyBehno1+dvzx36xuWfYQa/q+bb7k=
  api_key:
    secure: mlbsNzQ4IcTkxHnXtNJ6fBKyKqrRDF7kjCuGD1NFL+N/jjsUetCLLiWLPBG1DUrSxT0rqq9Y25+BSHj6V1QJFCZ9K48BvDxK3d3POaKsL7pqMXA/2a/MO4PEu6nDr45fsU3U0m8xgBJ4bZR/Ka8JxPKD4JnD/U+dkZfVL+sjvSGX5jyHwUAfKPW3pZjOVAMHlhb4jDYT9ndORC9CLrrp8kD9WsvVO5O48Wj7/rMBuezfg5fL3scT/p+hrR5cRgCsKcYQGXFS3FKsdte3mcEcJ46sVUUk6/o038QCJnEqB/nLFn+Bh6SS6BQREJUtEtV1A8tV0E17Od36uSB9hZ4ZqHRl9T8zcgVN7mFWeiysl8kvYWgmcf//H/Wroq3nAswFXFD6AIK6BRIl9BGUdHdxPL5LmrNFclhEgkF0Qw8bMzaR5W0dmhg4PC5hW+6yglRX5pYfVZadDQYvuKO79n3oFlClhwox4zZExV4Lhc1u1tKaMinBOhoEZVPz47XUg9/I0QHQgFLceo3iB6JckfDjrV5EHmsAmdCXNfGBMU0ADA27HD5w4dIeDDrfqWwwZ6R62Ext2WCRIwlS0FHH9LCPhHrRTAAMuUd5BM4MrUFhVKMhiyKKBmbv98pOC/XnjzxxgiO/vAAYbLLy5Q77MhbxApZtntb5KSqlPcLGUOUcEgA=
  on:
    tags: true
    repo: soulmaneller/nodejs-model-mysql
